#!/bin/bash
export NODE_ENV='production'
cd ../client
npm install
grunt release

cd ../server
npm install

# Invoke the Forever module (to START our Node.js server).
./node_modules/forever/bin/forever \
start \
-al forever.log \
-ao out.log \
-ae err.log \
server.js